version: "3"

services:
  mysql:
    container_name: go-api-mysql
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/sql:/sql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/log:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
